=== Johnny850807/XML-TriMago/Test XML/triMago.dtd
<!ELEMENT Waterball:WebSite (Waterball:restaurant*)>

<!ATTLIST Waterball:WebSite xmlns:Waterball CDATA #FIXED "http://g9.xml.csie.mcu.edu.tw">


<!ELEMENT Waterball:restaurant (Waterball:comment*)>

<!ATTLIST Waterball:restaurant id ID #REQUIRED>
<!ATTLIST Waterball:restaurant name CDATA #REQUIRED>
<!ATTLIST Waterball:restaurant latitude CDATA #REQUIRED>
<!ATTLIST Waterball:restaurant longitude CDATA #REQUIRED>
<!ATTLIST Waterball:restaurant price CDATA #REQUIRED>
<!ATTLIST Waterball:restaurant typeOfMeal CDATA #REQUIRED>
<!ATTLIST Waterball:restaurant address CDATA #REQUIRED>

<!ELEMENT Waterball:comment (Waterball:name+,Waterball:date+,Waterball:content+)>
<!ELEMENT Waterball:name (#PCDATA)>
<!ELEMENT Waterball:date (#PCDATA)>
<!ELEMENT Waterball:content (#PCDATA)>

<!ATTLIST Waterball:comment rate CDATA #REQUIRED>

=== Johnny850807/XML-TriMago/Test XML/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Waterball:WebSite SYSTEM "triMago.dtd">
<?xml-stylesheet type="text/xsl" href="index.xsl"?>
<Waterball:WebSite xmlns:Waterball="http://g9.xml.csie.mcu.edu.tw" >
	<Waterball:restaurant 
    id="r0" 
    name="癮食上癮" 
    latitude="24.9966" 
    longitude="121.336" 
    typeOfMeal="便當飯類" 
    price="80" 
    address="333台灣桃園市龜山區自強西路128號" >
		<Waterball:comment rate="3">
			<Waterball:name>水球</Waterball:name>
			<Waterball:date>2017/3/10</Waterball:date>
			<Waterball:content>很奇怪，他的椒麻雞，只是鹹酥雞+醬汁而已...</Waterball:content>
		</Waterball:comment>
	</Waterball:restaurant>
	<Waterball:restaurant 
    id="r1" 
    name="美國時間"  
    latitude="24.9966" 
    longitude="121.336" 
    typeOfMeal="早餐 早午餐" 
    price="40" 
    address="333台灣桃園市龜山區自強西路128號"
    imageUrl="http://imgur.com/download/JWjcrU7">
		<Waterball:comment rate="1">
			<Waterball:name>昇昇</Waterball:name>
			<Waterball:date>2017/3/15</Waterball:date>
			<Waterball:content>難吃，馬的。</Waterball:content>
		</Waterball:comment>
		<Waterball:comment rate="5">
			<Waterball:name>韋傑</Waterball:name>
			<Waterball:date>2017/4/18</Waterball:date>
			<Waterball:content>可以抽菸，還不錯。</Waterball:content>
		</Waterball:comment>
		<Waterball:comment rate="2">
			<Waterball:name>昇昇</Waterball:name>
			<Waterball:date>2017/4/19</Waterball:date>
			<Waterball:content>能抽菸又怎樣，沒抽菸你都買得起車了。</Waterball:content>
		</Waterball:comment>
  </Waterball:restaurant>
	<Waterball:restaurant 
    id="r2" 
    name="Waterball Dream"  
    latitude="24.992495" 
    longitude="121.339421" 
    typeOfMeal="早餐 早午餐" 
    price="340" 
    address="神之地址"
    imageUrl="http://imgur.com/download/tHEZ1hi">
		<Waterball:comment rate="5">
			<Waterball:name>Waterball</Waterball:name>
			<Waterball:date>2017/4/1</Waterball:date>
			<Waterball:content>Welcome here to have hthe most popular and romantic date!</Waterball:content>
		</Waterball:comment>
	</Waterball:restaurant>
	<Waterball:restaurant 
    id="r3" 
    name="享樂主義"  
    latitude="24.993181" 
    longitude="121.337116" 
    typeOfMeal="義大利麵" 
    price="70" 
    address="333台灣桃園市龜山區333桃園市龜山區中山街2號 333桃園市龜山區中山街2號"
    imageUrl="http://imgur.com/download/dUgGx8X">
		<Waterball:comment rate="4">
			<Waterball:name>大金 (Lee Po Yi)</Waterball:name>
			<Waterball:date>2014/1/17</Waterball:date>
			<Waterball:content>下次再來 如果我沒被21</Waterball:content>
		</Waterball:comment>
  </Waterball:restaurant>
  <Waterball:restaurant 
    id="r4" 
    name="Mr.Q"  
    latitude="24.988532" 
    longitude="121.343349" 
    typeOfMeal="早午餐" 
    price="40" 
    address="333台灣桃園市龜山區中山街5號"
    imageUrl="https://i.vimeocdn.com/portrait/4399054_300x300">
  </Waterball:restaurant>
	
</Waterball:WebSite>

=== Johnny850807/XML-TriMago/Test XML/triMago.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Waterball:WebSite SYSTEM "triMago.dtd">
<?xml-stylesheet type="text/xsl" href="index.xsl"?>
<Waterball:WebSite xmlns:Waterball="http://g9.xml.csie.mcu.edu.tw" >
	<Waterball:restaurant id="r0" name="癮食上癮" latitude="24.9966" longitude="121.336" typeOfMeal="便當飯類" price="80" address="333台灣桃園市龜山區自強西路128號">
		<Waterball:comment rate="3">
			<Waterball:name>水球</Waterball:name>
			<Waterball:date>2017/3/10</Waterball:date>
			<Waterball:content>很奇怪，他的椒麻雞，只是鹹酥雞+醬汁而已...</Waterball:content>
		</Waterball:comment>
	</Waterball:restaurant>
	<Waterball:restaurant id="r1" name="美國時間"  latitude="24.9966" longitude="121.336" typeOfMeal="早餐 早午餐" price="40" address="333台灣桃園市龜山區自強西路128號">
		<Waterball:comment rate="1">
			<Waterball:name>昇昇</Waterball:name>
			<Waterball:date>2017/3/15</Waterball:date>
			<Waterball:content>難吃，馬的。</Waterball:content>
		</Waterball:comment>
  </Waterball:restaurant>
	<Waterball:restaurant id="r2" name="Waterball Dream"  latitude="24.992495" longitude="121.339421" typeOfMeal="早餐 早午餐" price="340" address="神之地址">
		<Waterball:comment rate="5">
			<Waterball:name>Waterball</Waterball:name>
			<Waterball:date>2017/4/1</Waterball:date>
			<Waterball:content>Welcome here to have hthe most popular and romantic date!</Waterball:content>
		</Waterball:comment>
	</Waterball:restaurant>
	
</Waterball:WebSite>
