=== Johnny850807/XML-TriMago/TriMago/model/triMago.dtd
<!ELEMENT Waterball:WebSite (Waterball:restaurant*)>

<!ATTLIST Waterball:WebSite xmlns:Waterball CDATA #FIXED "http://g9.xml.csie.mcu.edu.tw">
<!ATTLIST Waterball:WebSite infoAmount CDATA #REQUIRED>
<!ATTLIST Waterball:WebSite siteRate CDATA #REQUIRED>

<!ELEMENT Waterball:restaurant (Waterball:comment*)>

<!ATTLIST Waterball:restaurant id ID #REQUIRED>
<!ATTLIST Waterball:restaurant name CDATA #REQUIRED>
<!ATTLIST Waterball:restaurant latitude CDATA #REQUIRED>
<!ATTLIST Waterball:restaurant longitude CDATA #REQUIRED>
<!ATTLIST Waterball:restaurant price CDATA #REQUIRED>
<!ATTLIST Waterball:restaurant typeOfMeal CDATA #REQUIRED>

<!ELEMENT Waterball:comment (Waterball:name+,Waterball:date+,Waterball:content+,Waterball:rate+)>
<!ELEMENT Waterball:name (#PCDATA)>
<!ELEMENT Waterball:date (#PCDATA)>
<!ELEMENT Waterball:content (#PCDATA)>
<!ELEMENT Waterball:rate (#PCDATA)>

=== Johnny850807/XML-TriMago/TriMago/model/triMago.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Waterball:WebSite SYSTEM "triMago.dtd">

<Waterball:WebSite 
	xmlns:Waterball="http://g9.xml.csie.mcu.edu.tw"
	infoAmount="0"
	siteRate="4">
	<Waterball:restaurant
		id="r0"
		name="癮食上癮"
		latitude="121.336" 
		longitude="24.9966"
		typeOfMeal="便當飯類"
		price="80">
		<Waterball:comment>
			<Waterball:name>水球</Waterball:name>
			<Waterball:date>2017/3/10</Waterball:date>
			<Waterball:content>很奇怪，他的椒麻雞，只是鹹酥雞+醬汁而已...</Waterball:content>
			<Waterball:rate>3</Waterball:rate>
		</Waterball:comment>
		
	</Waterball:restaurant>
	
	
	
	<Waterball:restaurant
		id="r1"
		name="美國時間"
		latitude="121.336" 
		longitude="24.9966"
		typeOfMeal="早餐 早午餐"
		price="40">
		<Waterball:comment>
			<Waterball:name>昇昇</Waterball:name>
			<Waterball:date>2017/3/15</Waterball:date>
			<Waterball:content>難吃，馬的。</Waterball:content>
			<Waterball:rate>1</Waterball:rate>
		</Waterball:comment>
	</Waterball:restaurant>
</Waterball:WebSite>
